version: '3.8'

services:
  web:
    build: ./app
    command: bash -c "gunicorn base.wsgi:application --bind 0.0.0.0:8000  --timeout 600"
    volumes:
      - ./app:/usr/src/app
      - static_volume:/usr/src/app/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    logging:
      driver: none
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: "hello_django_dev"
      POSTGRES_USER: "hello_django"
      POSTGRES_PASSWORD: "hello_django"
    logging:
      driver: none
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles
    ports:
      - 80:80
    depends_on:
      - web
    logging:
      driver: none

volumes:
  static_volume:
  postgres_data:
