version: '3.8'

services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    command: bash -c "python manage.py collectstatic --no-input --clear && gunicorn base.wsgi:application --bind 0.0.0.0:8000 "
    volumes:
      - static_volume:/usr/src/app/staticfiles
    expose:
      - 8000
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  static_volume: