# Generated by Django 4.0.8 on 2023-08-24 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='price',
            new_name='rank',
        ),
    ]
