# Generated by Django 4.0.8 on 2023-08-30 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0011_alter_currencytable_tf1_alter_currencytable_tf15_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencytable',
            name='tf1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='currencytable',
            name='tf15',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='currencytable',
            name='tf5',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Impulses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=5)),
                ('tf', models.IntegerField()),
                ('priceStart', models.FloatField()),
                ('dateStart', models.DateTimeField()),
                ('priceEnd', models.FloatField()),
                ('dateEnd', models.FloatField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screener.currency')),
            ],
        ),
    ]
