# Generated by Django 4.0.8 on 2023-08-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0012_alter_currencytable_tf1_alter_currencytable_tf15_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impulses',
            name='dateEnd',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='impulses',
            name='dateStart',
            field=models.CharField(max_length=20),
        ),
    ]
