# Generated by Django 4.0.8 on 2023-08-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0013_alter_impulses_dateend_alter_impulses_datestart'),
    ]

    operations = [
        migrations.AddField(
            model_name='impulses',
            name='isClose',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
