# Generated by Django 4.0.8 on 2023-08-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0002_rename_price_currency_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
