# Generated by Django 4.0.8 on 2023-08-24 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0005_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
