# Generated by Django 4.0.8 on 2023-08-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0006_machine_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candles',
            name='date',
            field=models.BigIntegerField(),
        ),
    ]
