# Generated by Django 4.0.8 on 2023-08-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0007_alter_candles_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='candles',
            name='tf',
            field=models.IntegerField(default=0),
        ),
    ]
