# Generated by Django 4.0.8 on 2023-09-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0015_remove_impulses_isclose_impulses_isopen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candles',
            name='Date',
            field=models.DateTimeField(),
        ),
    ]
