# Generated by Django 4.0.8 on 2023-09-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0016_alter_candles_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impulses',
            name='dateEnd',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='impulses',
            name='dateStart',
            field=models.DateTimeField(),
        ),
    ]
