# Generated by Django 4.0.8 on 2023-09-13 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0017_alter_impulses_dateend_alter_impulses_datestart'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=5)),
                ('price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screener.currency')),
            ],
        ),
    ]
