# Generated by Django 4.0.8 on 2023-09-13 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0018_bigorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigorders',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
